require("dotenv").config({ path: "../.env" });
const { db } = require("../config/firebase");

const jobTitles = [
  {
    category: "Education",
    titles: [
      "Teacher",
      "Tutor",
      "Mathematics Teacher",
      "English Teacher",
      "Science Teacher",
      "Physics Teacher",
      "Chemistry Teacher",
      "Biology Teacher",
      "Computer Science Teacher",
      "French Teacher",
      "Spanish Teacher",
      "Music Teacher",
      "Art Teacher",
      "Dance Teacher",
      "Piano Teacher",
      "Guitar Teacher",
      "Violin Teacher",
      "Singing Coach",
      "Driving Instructor",
      "Coding Instructor",
      "Exam Coach",
      "SAT Tutor",
      "IELTS Tutor",
      "TOEFL Tutor",
      "WAEC Tutor",
      "JAMB Tutor",
      "University Lecturer",
      "Special Education Teacher",
      "Montessori Teacher",
      "Early Childhood Educator",
      "Homework Helper",
    ],
  },
  {
    category: "Healthcare",
    titles: [
      "Doctor",
      "General Practitioner",
      "Surgeon",
      "Dentist",
      "Pharmacist",
      "Nurse",
      "Midwife",
      "Physiotherapist",
      "Occupational Therapist",
      "Speech Therapist",
      "Nutritionist",
      "Dietitian",
      "Psychologist",
      "Psychiatrist",
      "Counselor",
      "Medical Laboratory Scientist",
      "Radiographer",
      "Optometrist",
      "Ophthalmologist",
      "Pediatrician",
      "Dermatologist",
      "Cardiologist",
      "Neurologist",
      "Orthopedic Doctor",
      "Veterinary Doctor",
      "Caregiver",
      "Home Health Aide",
      "Ambulance Paramedic",
    ],
  },
  {
    category: "Legal & Finance",
    titles: [
      "Lawyer",
      "Barrister",
      "Solicitor",
      "Notary Public",
      "Accountant",
      "Chartered Accountant",
      "Auditor",
      "Tax Consultant",
      "Bookkeeper",
      "Financial Advisor",
      "Financial Planner",
      "Insurance Agent",
      "Mortgage Broker",
      "Investment Advisor",
      "Business Consultant",
      "Compliance Officer",
    ],
  },
  {
    category: "Construction & Skilled Trades",
    titles: [
      "Electrician",
      "Plumber",
      "Carpenter",
      "Bricklayer",
      "Mason",
      "Welder",
      "Iron Bender",
      "Roofer",
      "Tiler",
      "Painter",
      "POP Ceiling Installer",
      "Drywall Installer",
      "Flooring Installer",
      "Glazier",
      "Window Installer",
      "Aluminum Fabricator",
      "Furniture Maker",
      "Cabinet Maker",
      "Blacksmith",
      "Concrete Specialist",
      "Excavator Operator",
      "Crane Operator",
      "Scaffolder",
      "Borehole Driller",
      "Surveyor",
      "Quantity Surveyor",
      "Site Engineer",
      "Building Inspector",
      "Interior Finisher",
    ],
  },
  {
    category: "Home Services",
    titles: [
      "Cleaner",
      "Housekeeper",
      "Maid",
      "Laundry Service",
      "Ironing Service",
      "Cook",
      "Chef",
      "Private Chef",
      "Nanny",
      "Babysitter",
      "Elderly Caregiver",
      "Pet Sitter",
      "Dog Walker",
      "Gardener",
      "Landscaper",
      "Pool Cleaner",
      "Pest Control Technician",
      "Home Organizer",
      "Upholstery Cleaner",
      "Carpet Cleaner",
    ],
  },
  {
    category: "Automotive",
    titles: [
      "Mechanic",
      "Auto Electrician",
      "Panel Beater",
      "Spray Painter",
      "Car Detailer",
      "Tire Technician",
      "Car Wash Attendant",
      "Vehicle Inspector",
      "Tow Truck Driver",
      "Auto Glass Installer",
      "Motorcycle Mechanic",
      "Bicycle Repair Technician",
    ],
  },
  {
    category: "Technology",
    titles: [
      "Software Developer",
      "Mobile App Developer",
      "Web Developer",
      "Frontend Developer",
      "Backend Developer",
      "Full Stack Developer",
      "UI Designer",
      "UX Designer",
      "Graphic Designer",
      "Product Designer",
      "Cybersecurity Specialist",
      "Network Engineer",
      "IT Support Technician",
      "Computer Repair Technician",
      "Data Analyst",
      "Data Scientist",
      "AI Engineer",
      "Machine Learning Engineer",
      "Cloud Engineer",
      "DevOps Engineer",
      "Database Administrator",
      "System Administrator",
      "Blockchain Developer",
      "Game Developer",
      "SEO Specialist",
      "Digital Marketer",
      "Social Media Manager",
      "Content Writer",
      "Copywriter",
      "Technical Writer",
      "Virtual Assistant",
      "Video Editor",
      "Motion Graphics Designer",
      "Animator",
      "Photographer",
      "Videographer",
    ],
  },
  {
    category: "Beauty & Fashion",
    titles: [
      "Barber",
      "Hair Stylist",
      "Makeup Artist",
      "Nail Technician",
      "Lash Technician",
      "Esthetician",
      "Skincare Specialist",
      "Spa Therapist",
      "Massage Therapist",
      "Tattoo Artist",
      "Piercing Specialist",
      "Fashion Designer",
      "Tailor",
      "Seamstress",
      "Cobbler",
      "Wig Maker",
      "Braider",
    ],
  },
  {
    category: "Events",
    titles: [
      "Event Planner",
      "Wedding Planner",
      "MC",
      "DJ",
      "Live Band",
      "Saxophonist",
      "Pianist",
      "Drummer",
      "Violinist",
      "Comedian",
      "Magician",
      "Event Decorator",
      "Florist",
      "Caterer",
      "Bartender",
      "Waiter",
      "Waitress",
      "Usher",
      "Bouncer",
      "Event Security",
      "Photographer",
      "Videographer",
    ],
  },
  {
    category: "Business Services",
    titles: [
      "Business Coach",
      "Career Coach",
      "Life Coach",
      "HR Consultant",
      "Recruiter",
      "Translator",
      "Interpreter",
      "Personal Assistant",
      "Executive Assistant",
      "Receptionist",
      "Customer Support Agent",
      "Telemarketer",
      "Sales Representative",
      "Procurement Officer",
      "Supply Chain Consultant",
    ],
  },
  {
    category: "Security",
    titles: [
      "Security Guard",
      "Bodyguard",
      "Private Investigator",
      "CCTV Installer",
      "Locksmith",
      "Fire Safety Technician",
      "Alarm System Installer",
    ],
  },
  {
    category: "Agriculture",
    titles: [
      "Farmer",
      "Poultry Farmer",
      "Fish Farmer",
      "Livestock Farmer",
      "Beekeeper",
      "Agronomist",
      "Irrigation Specialist",
      "Farm Equipment Operator",
      "Veterinarian",
      "Animal Trainer",
    ],
  },
  {
    category: "Delivery & Transport",
    titles: [
      "Taxi Driver",
      "Chauffeur",
      "Truck Driver",
      "Delivery Rider",
      "Courier",
      "Bus Driver",
      "Boat Captain",
      "Moving Service",
      "Furniture Mover",
      "Logistics Coordinator",
    ],
  },
  {
    category: "Manufacturing & Industrial",
    titles: [
      "Machine Operator",
      "CNC Operator",
      "Factory Worker",
      "Quality Control Inspector",
      "Production Supervisor",
      "Industrial Electrician",
      "Industrial Mechanic",
      "Forklift Operator",
    ],
  },
  {
    category: "Creative Arts",
    titles: [
      "Artist",
      "Illustrator",
      "Sculptor",
      "Calligrapher",
      "Voice Actor",
      "Actor",
      "Film Director",
      "Screenwriter",
      "Music Producer",
      "Sound Engineer",
      "Podcast Editor",
    ],
  },
  {
    category: "Fitness & Sports",
    titles: [
      "Personal Trainer",
      "Gym Instructor",
      "Yoga Instructor",
      "Pilates Instructor",
      "Swimming Coach",
      "Football Coach",
      "Basketball Coach",
      "Tennis Coach",
      "Martial Arts Instructor",
      "Boxing Coach",
      "Referee",
    ],
  },
  {
    category: "Religious & Community",
    titles: ["Pastor", "Imam", "Priest", "Chaplain", "Marriage Counselor"],
  },
  {
    category: "Repair Services",
    titles: [
      "Appliance Repair Technician",
      "Refrigerator Technician",
      "Air Conditioner Technician",
      "Generator Repair Technician",
      "TV Repair Technician",
      "Phone Repair Technician",
      "Laptop Repair Technician",
      "Printer Repair Technician",
      "Watch Repair Technician",
      "Clock Repair Technician",
      "Sewing Machine Repair Technician",
    ],
  },
  {
    category: "Real Estate",
    titles: [
      "Real Estate Agent",
      "Property Manager",
      "Estate Surveyor",
      "Property Valuer",
      "Mortgage Consultant",
    ],
  },
  {
    category: "Specialized Services",
    titles: [
      "Drone Pilot",
      "Drone Photographer",
      "Genealogist",
      "Archivist",
      "Sommelier",
      "Barista",
      "Baker",
      "Pastry Chef",
      "Chocolatier",
      "Butcher",
      "Fishmonger",
      "Locksmith",
      "Goldsmith",
      "Jeweler",
      "Gemologist",
      "Auctioneer",
      "Customs Broker",
      "Travel Agent",
      "Tour Guide",
      "Visa Consultant",
    ],
  },
];

const seedJobTitles = async () => {
  try {
    console.log("Seeding job titles...");
    const batch = db.batch();

    jobTitles.forEach((categoryData) => {
      const docRef = db.collection("jobTitles").doc();
      batch.set(docRef, {
        category: categoryData.category,
        titles: categoryData.titles,
        createdAt: new Date(),
      });
    });

    await batch.commit();
    console.log("Job titles seeded successfully!");
    process.exit(0);
  } catch (error) {
    console.error("Error seeding job titles:", error.message);
    process.exit(1);
  }
};

seedJobTitles();
